---
# =======================
#      BLOCK REWARDS
# =======================
# 1. An advanced plugin with wiki to add reward on player break block
# 2. If you see errors, report here: https://github.com/Henry12960/BlockReward/issues/new
# 3. Plugin made by Henry Thierry [HenryDM] 
# 4. Plugin Wiki: https://github.com/Henry12960/BlockReward/wiki
# 5. Henry's Website: https://github.com/Henry12960

# =======================
#         GENERAL
# =======================
# 1. If you set "block-break-reward" to false this function will be disabled
# 2. If you set "block-place-reward" to false this function will be disabled

block-break-rewards: true
block-place-rewards: true
blocks: ["TNT", "DIAMOND_BLOCK", "EMERALD_BLOCK"]

# =======================
#        CHANCES
# =======================
# 1. You can set all chances from 1 to 100

add-money-chance-value: 20
reduce-money-chance-value: 5
add-item-chance-value: 30
command-chance-value: 2
add-xp-chance-value: 60
remove-xp-chance-value: 20

# =======================
#       BLOCK BREAK
# =======================
# 1. All addons are disabled! Change to true to enable

block-break-add-money: false
block-break-add-money-amount: 10
block-break-add-money-worlds: ["AddMoneyWorld", "AddMoneyExample"]

block-break-reduce-money: false
block-break-reduce-money-amount: 5
block-break-reduce-money-worlds: ["ReduceMoneyWorld", "ReduceMoneyExample"]

block-break-add-item: false
block-break-add-item-id: 264
block-break-add-item-amount: 2
block-break-add-item-worlds: ["AddItemWorld", "AddItemExample"]

block-break-command: false
block-break-command-trigger: "tell {player} Hi! {line} Command example." 

block-break-add-xp: false
block-break-add-xp-value: 1
block-break-add-xp-worlds: ["AddXpWorld", "AddXpExample"]

block-break-remove-xp: false
block-break-remove-xp-value: 1
block-break-remove-xp-worlds: ["RemoveXpWorld", "RemoveXpExample"]

# =======================
#      BLOCK PLACE
# =======================
# 1. All addons are disabled! Change to true to enable

block-place-add-money: false
block-place-add-money-amount: 10
block-place-add-money-worlds: ["AddMoneyWorld", "AddMoneyExample"]

block-place-reduce-money: false
block-place-reduce-money-amount: 5
block-place-reduce-money-worlds: ["ReduceMoneyWorld", "ReduceMoneyExample"]

block-place-add-item: false
block-place-add-item-id: 264
block-place-add-item-amount: 2
block-placea-add-item-worlds: ["AddItemWorld", "AddItemExample"]

block-place-command: false
block-place-command-trigger: "tell {player} Hi! {line} Command example." 

block-place-add-xp: false
block-place-add-xp-value: 1
block-place-add-xp-worlds: ["AddXpWorld", "AddXpExample"]

block-place-remove-xp: false
block-place-remove-xp-value: 1
block-place-remove-xp-worlds: ["RemoveXpWorld", "RemoveXpExample"]
...